### ISSUE TITLE
Jar file generated by make file failed to run

### ISSUE THREAD

**Issue by bijaychamlagain** [inft3063-assignment-1-wed-atb/INFT2063_Assignment_1-v02#27]
The jar program generated by the makefile failed to run and shows the following error.

```
Exception in thread "main" java.lang.NoClassDefFoundError: Report
	at CashRegister.main(CashRegister.java:19)
Caused by: java.lang.ClassNotFoundException: Report
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 1 more
```

Looks like it is the error in the makefile and missing some classes.

**Comment by bijaychamlagain** [comment]
The makefile was missing the new class that were created later. Makefile is creating jar files and jar files are running fine.
